services:
  ubuntu:
    container_name: ubuntu
    image: pokerdice-ubuntu
    tty: true

  pokerdice-postgres:
    container_name: pokerdice-postgres
    image: pokerdice-postgres
    environment:
      - POSTGRES_USER=pokerdice
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5432:5432
  pokerdice-jvm:
    container_name: pokerdice-jvm
    hostname: pokerdice-jvm
    image: pokerdice-jvm
    environment:
      PORT: 8080
      DB_URL: "jdbc:postgresql://pokerdice-postgres:5432/db?user=pokerdice&password=password"
    ports:
      - 8080:8080
